"""unique shop name

Revision ID: 7f9af294d7b0
Revises: 77bea9ac6df5
Create Date: 2026-05-21 21:18:44.886560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9af294d7b0'
down_revision: Union[str, Sequence[str], None] = '77bea9ac6df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_unique_constraint('uq_product_slug_seller', 'products', ['slug', 'seller_id'])
    op.create_unique_constraint(None, 'seller_applications', ['shop_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller_applications', type_='unique')
    op.drop_constraint('uq_product_slug_seller', 'products', type_='unique')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # ### end Alembic commands ###
